require_relative 'config/application.rb'
require_relative 'queue/rabbitmq_connection_subscriber'

task default: %w[consume_invoices]

task :consume_invoices do
	QueueConnectionSubscriber.subscribe
end