# Gemfile
source 'https://rubygems.org'

gem 'rack'
gem 'pg' ## Postgres gem for the database
gem 'sequel' ## Thin ORM to connect to db, read from db etc
gem 'bunny' ## Ruby gem for rabbitMQ
gem 'hanami-router'
gem 'hanami-controller'